### ISSUE TITLE
Exercice 5 - Count votes

### ISSUE THREAD

**Issue by pticao** [LDSSA/batch2-blu10#1]
created a boolean array of votes >0 (shape = (671, 9066))
then sum all rows (per column) (shape = (9066, ))

Shouldn't return one dimension array (9066, ) instead of two dimension (1, 9066)?
even after reshaping to (1, 9066) all asserts fail...

**Comment by hugorcf** [comment]
I got the first assert to work (the one which checks the shape) but all the others also fail. But the strange thing is that questions 10 to 12 depend on the result of Q5 but I pass all the asserts on these questions. Maybe there is some error with the asserts of Q5?

**Comment by pticao** [comment]
Did you do reshape, in order to get (1, 9066)?

**Comment by hugorcf** [comment]
I did.

**Comment by pticao** [comment]
Found out that you do not need reshape... if you use numpy function instead with keepdims=True
:)

**Comment by hugorcf** [comment]
I still get all the other asserts wrong though :(

**Comment by orlandocosta76** [comment]
Hi, I also had the same problem, but I submitted the notebook and got all answers correct, event though only first assert passes, a little misleading (and annoying :)

**Comment by vascosmota** [comment]
So, @pticao the initial issue you reported is not a bug. As mentioned you need to reshape your array correctly.

However, the issue reported by @hugorcf  and @orlandocosta76 is very real and I faced it myself. We will try to understand better why this is happening.

For now, bear in mind that you might get these assertions wrong with a correct code (as @orlandocosta76 experienced).

**Comment by joaobcampos** [comment]
Hi. I would also like to note that passing or not in the asserts seems to depend on the system or configuration you are working on. In this question I have the same code in a windows and linux. On linux it passes the asserts. On windows, it doesn't.

**Comment by FilipaRodrigues** [comment]
I had the same problem with Q5, but unlike you I can't pass the asserts of Q10, and so on, and when I submitted I only got 10.
I've taken some time to understand what could be wrong, but I keep not passing the asserts ...

UPDATE: Now I managed to pass all the asserts, except the ones of Q5 (except the one that verifies the shape), but I keep getting 10 on the submission.

**Comment by meddulla** [comment]
@FilipaRodrigues Had similar problems. In my case, I was either getting a matrix when I should be getting a vector, or getting a vector when I should be returning the value directly.
