### ISSUE TITLE
Q12 expects the top N to be sorted from largest to smallest 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/batch2-blu10#3]
On Q12 you need to return the top N in order `[largest, 2nd largest, 3rd largest, ...]`, otherwise the assert won't pass. 

If you've done the slicing in a way that changes that, try typing them out in order (you know which is the biggest one from Q11) and see if it passes the assert.

**Comment by joaobcampos** [comment]
From question 11, I can observe the values. The problem is, in question 12, when I obtain the values requested, somehow, it doesn't pass the assert.
